import React, { useEffect, useState } from 'react';
import {
    FileText, ShieldCheck, ShieldAlert, Activity, GitCommit, Search, List
} from 'lucide-react';
import RiskScoreCard from '../components/RiskScoreCard';

const Reports = () => {
    const [report, setReport] = useState(null);

    useEffect(() => {
        // In prototype, pull the freshly generated RAG pipeline report from storage
        const stored = localStorage.getItem('lastReport');
        if (stored) {
            setReport(JSON.parse(stored));
        }
    }, []);

    if (!report) {
        return (
            <div className="flex flex-col items-center justify-center p-16 text-center animate-fade-in">
                <div className="p-6 bg-white/5 rounded-full mb-4 border border-white/10">
                    <Search className="w-12 h-12 text-slate-500" />
                </div>
                <h2 className="text-xl font-semibold text-white">No Active Report Selected</h2>
                <p className="text-slate-400 mt-2">Run a new diagnosis through the Upload engine to view detailed RAG reasoning here.</p>
            </div>
        );
    }

    // Backend returns confidence_score as 0.0-1.0 float, multiply by 100 for display
    const rawConf = report?.confidence_score ?? report?.confidence_calibration?.overall_confidence ?? 0;
    const confidencePercent = rawConf <= 1.0 ? rawConf * 100 : rawConf;
    const isHighConfidence = confidencePercent > 70;
    const confidenceScore = confidencePercent.toFixed(1);

    // Derive risk_level from risk_score if not explicitly provided
    const rawRisk = report?.risk_score ?? 0;
    const riskPercent = rawRisk <= 1.0 ? rawRisk * 100 : rawRisk;
    const riskLevel = report?.risk_level ?? (riskPercent > 70 ? 'High' : riskPercent > 40 ? 'Medium' : 'Low');

    return (
        <div className="space-y-6 animate-fade-in pb-8">
            {/* Header */}
            <div>
                <h1 className="text-2xl font-bold text-white tracking-tight flex items-center">
                    <FileText className="mr-3 text-brand-500" /> Diagnosis Inference Report
                </h1>
                <p className="text-slate-400 mt-1">Generated by MedRAG Orchestrator</p>
            </div>

            {/* Top Banner Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {/* Confidence Calibration */}
                <div className={`glass-panel border p-5 relative overflow-hidden ${isHighConfidence ? 'border-success/30' : 'border-warning/30'}`}>
                    <div className={`absolute -right-4 -top-4 w-24 h-24 rounded-full blur-2xl opacity-20 ${isHighConfidence ? 'bg-success' : 'bg-warning'}`}></div>
                    <div className="flex items-center space-x-3 mb-2 text-sm font-semibold uppercase tracking-wider text-slate-400">
                        {isHighConfidence ? <ShieldCheck className="text-success w-5 h-5" /> : <ShieldAlert className="text-warning w-5 h-5" />}
                        <span>Engine Confidence</span>
                    </div>
                    <div className="flex items-end space-x-2 mt-4">
                        <span className={`text-4xl font-bold tracking-tight ${isHighConfidence ? 'text-success' : 'text-warning'}`}>{confidenceScore}</span>
                        <span className="text-slate-400 font-medium mb-1">%</span>
                    </div>
                </div>

                {/* Hallucination Flag */}
                <div className="glass-panel border border-white/10 p-5 flex flex-col justify-center">
                    <div className="flex items-center space-x-3 mb-2 text-sm font-semibold uppercase tracking-wider text-slate-400">
                        <GitCommit className="text-brand-500 w-5 h-5" />
                        <span>Hallucination Audit</span>
                    </div>
                    <p className="mt-2 text-lg font-medium">
                        {(report?.hallucination_score ?? 0) > 0.5 || report?.hallucination_audit?.hallucination_detected ? (
                            <span className="text-danger flex items-center"><ShieldAlert size={18} className="mr-2" /> Flagged Mismatch</span>
                        ) : (
                            <span className="text-success flex items-center"><ShieldCheck size={18} className="mr-2" /> Verifier Passed</span>
                        )}
                    </p>
                    <p className="text-xs text-slate-500 mt-1 truncate">
                        {report?.hallucination_audit?.message || `Score: ${((report?.hallucination_score ?? 0) * 100).toFixed(1)}% — No issues found.`}
                    </p>
                </div>

                {/* Extracted Risk */}
                <RiskScoreCard
                    score={riskPercent}
                    level={riskLevel}
                />
            </div>

            {/* Core Body - Reasoning vs Evidence Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mt-6">

                {/* Main Final Report Display */}
                <div className="lg:col-span-8 glass-panel border border-white/10 overflow-hidden flex flex-col">
                    <div className="px-6 py-4 bg-white/5 border-b border-white/10">
                        <h3 className="font-bold border-l-4 border-brand-500 pl-3 leading-none text-white">
                            Synthesized Clinical Evaluation
                        </h3>
                    </div>
                    <div className="p-6 flex-1 overflow-y-auto max-h-[600px] prose prose-invert max-w-none">
                        {/* Split report by double newlines for basic paragraph styling if purely text */}
                        {String(report?.final_report || report?.diagnosis_reasoning || report?.diagnosis || "No final text generated").split('\n\n').map((para, i) => (
                            <p key={i} className="text-slate-300 leading-relaxed mb-4">{para}</p>
                        ))}
                    </div>
                </div>

                {/* Right Sidebar - Retrieved Context */}
                <div className="lg:col-span-4 space-y-6">
                    {/* Original Query */}
                    <div className="glass-panel border border-white/10 p-5">
                        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">Original Clinical Query</h4>
                        <p className="text-sm font-medium text-slate-300 italic">"{report?.query}"</p>
                    </div>

                    {/* RAG Context Sources */}
                    <div className="glass-panel border border-white/10 overflow-hidden flex flex-col h-[470px]">
                        <div className="px-5 py-3 bg-white/5 border-b border-white/10 flex items-center justify-between">
                            <span className="font-semibold text-sm text-slate-300 flex items-center">
                                <List className="w-4 h-4 mr-2" /> Cited Evidence Sources
                            </span>
                        </div>
                        <div className="p-4 overflow-y-auto text-xs font-mono text-slate-400 space-y-3 whitespace-pre-wrap leading-relaxed">
                            {report?.retrieved_context_used || "No vector context injected during generation."}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
};

export default Reports;
